In [2]:
import torch
import numpy as np
torch.cuda.is_available()

False

In [2]:
data = [[1,2],[3,4],[5,6]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0599, 0.0822],
        [0.7763, 0.2561],
        [0.1597, 0.4245]]) 



In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1596, 0.7496, 0.2604],
        [0.1944, 0.8492, 0.4363]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [10]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
        	  [7, 8, 9]])
print("A的维度为{}" .format(A.dim()))
print("A形状为{}" .format(A.shape))
B = torch.tensor([[12, 22, 33],
        	  [44, 55, 66],
                  [77, 88,99]])
print("B的维度为{}" .format(B.dim()))

A的维度为2
A形状为torch.Size([3, 3])
B的维度为2


In [12]:
result1 = torch.stack((A,B),dim=0)
print("result1的维度为{}" .format(result1.dim()))
print("result1形状为{}" .format(result1.shape))
print("result1为{}" .format(result1))

result1的维度为3
result1形状为torch.Size([2, 3, 3])
result1为tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[12, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]])


In [13]:
result2 = torch.stack((A,B),dim=1)
print("result2的维度为{}" .format(result2.dim()))
print("result2形状为{}" .format(result2.shape))
print("result2为{}" .format(result2))

result2的维度为3
result2形状为torch.Size([3, 2, 3])
result2为tensor([[[ 1,  2,  3],
         [12, 22, 33]],

        [[ 4,  5,  6],
         [44, 55, 66]],

        [[ 7,  8,  9],
         [77, 88, 99]]])


In [14]:
result3 = torch.stack((A,B),dim=2)
print("result3的维度为{}" .format(result3.dim()))
print("result3形状为{}" .format(result3.shape))
print("result3为{}" .format(result3))

result3的维度为3
result3形状为torch.Size([3, 3, 2])
result3为tensor([[[ 1, 12],
         [ 2, 22],
         [ 3, 33]],

        [[ 4, 44],
         [ 5, 55],
         [ 6, 66]],

        [[ 7, 77],
         [ 8, 88],
         [ 9, 99]]])


In [15]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [18]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [19]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

In [22]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [3]:
torch.randn(5)

tensor([ 0.5649, -2.1456,  1.5311, -1.2193, -1.9009])

In [5]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])